server:
  port: ${SERVER_PORT:8080}

spring:
  output:
    ansi:
      enabled: ALWAYS

management:
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: [health, prometheus]
  metrics:
    export:
      prometheus:
        enabled: ${PROMETHEUS_ENABLED:true}

logging:
  pattern:
    level: '%5p%X{reqId}'
  level:
    pub.edholm.eiscprest: ${LOG_LEVEL:TRACE}

eiscp:
  receiver:
    hostname: 10.10.10.57
    port: 60128