server:
  port: ${SERVER_PORT:8080}

spring:
  output:
    ansi:
      enabled: ALWAYS

logging:
  pattern:
    level: '%5p%X{reqId}'
  level:
    pub.edholm.eiscprest: ${LOG_LEVEL:TRACE}

eiscp:
  receiver:
    hostname: 10.10.10.57
    port: 60128