spring:
  output:
    ansi:
      enabled: ALWAYS

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    pub.edholm.eiscprest: ${LOG_LEVEL:DEBUG}

eiscp:
  receiver:
    hostname: 10.10.10.57
    port: 60128